### ISSUE TITLE
teragence sdk also import Apache http which is more than 6k methods

### ISSUE THREAD

**Issue by ChristopheVersieux** [Teragence/android-sdk#1]
Hello

I just noticed that importing  teragence sdk also brings the apache libraby with more than 6k methods
As the dex limit is 65k methods in our applications, that means that we have imported something that is close to 10% of the limit

So, there is no problem using multidex at the end, but maybe there can be some optimisations done? Or use HttpURLConnection class instead ?
https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-apache-http-client

On the left, (mostly yellow), you can see the 2 charts where we I have 73841 methods and a zoom on Apache
While on the right (mostly blue) there is no org.apache inside the lib.

![capture](https://user-images.githubusercontent.com/356214/40613832-740de60c-6280-11e8-9cc9-c66af209eb8f.PNG)

**Comment by aslipchenko** [comment]
Hello Christophe,
Thanks for the comment. We'll have a look.

**Comment by aslipchenko** [comment]
Hello @ChristopheVersieux  -- starting from v1.0.5.31 we no longer use Apache http client.
